// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
    BaseLink: typeof import('./src/components/BaseLink.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    FormStartDeal: typeof import('./src/components/Form/StartDeal.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LayoutTabContent: typeof import('./src/components/Layout/TabContent.vue')['default']
    LayoutViews: typeof import('./src/components/Layout/Views.vue')['default']
    LoadingSplash: typeof import('./src/components/LoadingSplash.vue')['default']
    ModalAccount: typeof import('./src/components/Modal/Account.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spacer: typeof import('./src/components/Spacer.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
    TabContentPastDeals: typeof import('./src/components/TabContent/PastDeals.vue')['default']
    TabContentProposals: typeof import('./src/components/TabContent/Proposals.vue')['default']
    TabContentRunningDeals: typeof import('./src/components/TabContent/RunningDeals.vue')['default']
  }
}

export {}
